export const plantData = [
  {
    id: 1,
    name: "Aloe Vera",
    origin: "Arabian Peninsula",
    climaticCondition: "Tropical, arid",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1402438010/photo/aloe-vera-plant.jpg?s=612x612&w=0&k=20&c=Z7nq8Z4jJlLcvFC6lFgsHke1ZIcOTB_Dd7aYb5wtyWw=",
video: "https://www.pexels.com/video/footage-of-aloe-vera-in-a-vase-6953532/",
    purpose: "Medicinal, skincare",
    medicinalProperty: "Soothing burns, skin healing, digestive aid",
  },
  {
    id: 2,
    name: "Basil",
    origin: "India",
    climaticCondition: "Tropical, warm",
    availability: "Common",
    image: "https://media.istockphoto.com/id/843955686/photo/thai-holy-basil-flowering-shining-over-dark-background.jpg?s=612x612&w=0&k=20&c=0ss20SutAmY6JNrxdLoWGAEgs5-SI-VKFUXyjzkW1ZA=",
video: "https://www.shutterstock.com/shutterstock/videos/3551101157/preview/stock-footage-closeup-of-flora-of-holy-basil-plant-in-garden-in-rainy-season-background-tulsi-used-in-ayurveda.webm",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Anti-inflammatory, digestion aid",
  },
  {
    id: 3,
    name: "Rosemary",
    origin: "Mediterranean",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/503780310/photo/rosemary.jpg?s=612x612&w=0&k=20&c=uAcZOP9Chp4vLNx4EJHvmEkhu4HGw6nXL7xxR3aEWk0=",
video: "",
    purpose: "Culinary, ornamental",
    medicinalProperty: "Improves memory, circulation",
  },
  {
    id: 4,
    name: "Lavender",
    origin: "Mediterranean",
    climaticCondition: "Temperate, dry",
    availability: "Common",
    image: "https://media.istockphoto.com/id/2143731209/photo/lavender-flowers-close-up-on-sky-background.webp?b=1&s=612x612&w=0&k=20&c=Q_EsWqgbDnlpA4jvxgMfgNORQDbd7Cd2HedwlR4TVd4=",
video: "",
    purpose: "Aromatherapy, ornamental",
    medicinalProperty: "Stress relief, sleep aid",
  },
  {
    id: 5,
    name: "Peppermint",
    origin: "Europe, Middle East",
    climaticCondition: "Temperate, moist",
    availability: "Common",
    image: "https://media.istockphoto.com/id/478775140/photo/fresh-mint-on-a-wooden-table.jpg?s=612x612&w=0&k=20&c=6Prm-8OtMLpP3avlUnYlCU_oY5Jyq9ls8Rr4grdSNCo=",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Relieves headaches, digestive aid",
  },
  {
    id: 6,
    name: "Chamomile",
    origin: "Europe, Asia",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/544125236/photo/german-tea-chamomila-flowers-on-meadow.jpg?s=612x612&w=0&k=20&c=AsxXrNWVYoRpulm4zUATO8UQigORqd8xfPnnaMvdWDc=",
video: "",
    purpose: "Herbal tea, medicinal",
    medicinalProperty: "Sleep aid, digestive relief",
  },
  {
    id: 7,
    name: "Ginger",
    origin: "Southeast Asia",
    climaticCondition: "Tropical, warm",
    availability: "Common",
    image: "https://png.pngtree.com/thumb_back/fh260/background/20230607/pngtree-the-roots-of-ginger-shoots-are-growing-in-the-soil-image_2904836.jpg",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Anti-inflammatory, nausea relief",
  },
  {
    id: 8,
    name: "Echinacea",
    origin: "North America",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1273007054/photo/echinacea-purpurea-flowering-coneflowers-group-of-plants-in-bloom.jpg?s=612x612&w=0&k=20&c=OUGbZERqi1TaVXziewDLmk0sIqYZIGPRY9pL_VBcz5M=",
video: "",
    purpose: "Immune support, ornamental",
    medicinalProperty: "Boosts immune system, cold relief",
  },
  {
    id: 9,
    name: "Turmeric",
    origin: "India, Southeast Asia",
    climaticCondition: "Tropical, warm",
    availability: "Common",
    image: "https://t3.ftcdn.net/jpg/03/30/30/94/360_F_330309413_1GCy01jOT01AQWNVLoMQSluhmmXNSKFJ.jpg",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Anti-inflammatory, antioxidant",
  },
  {
    id: 10,
    name: "Mint",
    origin: "Europe, Asia",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1690922790/photo/looking-from-above-on-the-tops-of-the-leaves-of-a-mint-plant.webp?b=1&s=612x612&w=0&k=20&c=pE9PN1sH8Ld08OltLVXRVNUccNsu-tRIPdWJFaQKL4A=",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Digestive aid, freshens breath",
  },
  {
    id: 11,
    name: "Ginseng",
    origin: "East Asia, North America",
    climaticCondition: "Temperate, cool",
    availability: "Common",
    image: "https://png.pngtree.com/background/20230519/original/pngtree-plant-with-long-roots-growing-out-of-the-soil-picture-image_2656805.jpg",
video: "",
    purpose: "Medicinal, energy booster",
    medicinalProperty: "Enhances energy, reduces stress",
  },
  {
    id: 12,
    name: "Sage",
    origin: "Mediterranean",
    climaticCondition: "Temperate, dry",
    availability: "Common",
    image: "https://media.istockphoto.com/id/880551512/photo/fresh-sage-in-the-herb-garden.jpg?s=612x612&w=0&k=20&c=wniybCTgWCbYUpWHj-eRdoogj8qLBpn-0TKY5a4UdUw=",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Cognitive support, anti-inflammatory",
  },
  {
    id: 13,
    name: "Thyme",
    origin: "Mediterranean",
    climaticCondition: "Temperate, dry",
    availability: "Common",
    image: "https://img.freepik.com/premium-photo/fresh-raw-thyme-plant-thymus-vulgaris-flower-pot-isolated-white-background_131238-928.jpg",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Antimicrobial, respiratory support",
  },
  {
    id: 14,
    name: "Fenugreek",
    origin: "South Europe, West Asia",
    climaticCondition: "Temperate, warm",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1285888022/photo/fenugreek-seeds-and-plant-on-a-old-wooden-background.jpg?s=612x612&w=0&k=20&c=uRUQPgQtEevgbrh4H-Msh5lv7HibigXNIQd9fqfdkRk=",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Supports digestion, regulates blood sugar",
  },
  {
    id: 15,
    name: "Ashwagandha",
    origin: "India, Middle East",
    climaticCondition: "Dry, sub-tropical",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1322331981/photo/withania-somnifera-growing-in-field-india-winter-cherry-fruit-and-leaves-used-to-increase.jpg?s=612x612&w=0&k=20&c=WQa-vrfnhbj_p8ys5vjRu86iHyMAUYvhdlsvsaTwFbQ=",
video: "",
    purpose: "Medicinal",
    medicinalProperty: "Stress relief, enhances vitality",
  },
  {
    id: 16,
    name: "Neem",
    origin: "Indian subcontinent",
    climaticCondition: "Tropical, arid",
    availability: "Common",
    image: "https://onszaden.com//Files/10/221000/221010/ProductPhotos/Large/1763410857.jpg",
video: "",
    purpose: "Medicinal, pesticide",
    medicinalProperty: "Anti-bacterial, immune booster",
  },
  {
    id: 17,
    name: "Holy Basil (Tulsi)",
    origin: "India",
    climaticCondition: "Tropical, warm",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1253676637/photo/holy-basil.jpg?s=612x612&w=0&k=20&c=4kZxa85rXwQ1yBZIgxKy8q3gHRrH796dTsZrVCUOoIs=",
video: "",
    purpose: "Religious, medicinal",
    medicinalProperty: "Stress relief, respiratory aid",
  },
  {
    id: 18,
    name: "Licorice",
    origin: "Southern Europe, Asia",
    climaticCondition: "Temperate, arid",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1297090436/photo/licorice-branch-and-roots.jpg?s=612x612&w=0&k=20&c=UaNsQkgHdHzwkp35zJ2xzWhQior0INWjJPMQ6A2rETI=",
video: "",
    purpose: "Medicinal, flavoring",
    medicinalProperty: "Soothes sore throat, aids digestion",
  },
  {
    id: 19,
    name: "Lemongrass",
    origin: "India, Sri Lanka",
    climaticCondition: "Tropical, warm",
    availability: "Common",
    image: "https://png.pngtree.com/thumb_back/fw800/background/20240411/pngtree-lemon-grass-plant-green-leaf-background-image_15657437.jpg",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Aids digestion, relieves stress",
  },
  {
    id: 20,
    name: "Jasmine",
    origin: "Asia, Europe",
    climaticCondition: "Tropical, warm",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1158028412/photo/arabian-jasmine-plants-2-jasmines-very-grown-and-others-fallen-down.jpg?s=612x612&w=0&k=20&c=-wSGYIBNTpab2rbF1r8Z20R7w5FkPOUtZdQtr9GgYqA=",
video: "",
    purpose: "Aromatherapy, ornamental",
    medicinalProperty: "Calming, stress relief",
  },
  {
    id: 21,
    name: "Cilantro",
    origin: "Mediterranean",
    climaticCondition: "Temperate, moist",
    availability: "Common",
    image: "https://media.istockphoto.com/id/184908546/photo/cilantro.jpg?s=612x612&w=0&k=20&c=T8SyTairzfiq8fyWw1soeyEFmy664bw8CtKBTpTixjQ=",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Digestive aid, anti-inflammatory",
  },
  {
    id: 22,
    name: "Parsley",
    origin: "Mediterranean",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1198833526/photo/parsley-growing-at-a-farm.jpg?s=612x612&w=0&k=20&c=h040A7PC11xh7DYu-zUinaIaz2Gp0IUNihlpXNI7b2I=",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Rich in vitamins, aids digestion",
  },
  {
    id: 23,
    name: "Oregano",
    origin: "Mediterranean",
    climaticCondition: "Temperate, dry",
    availability: "Common",
    image: "https://cdn.fleursdelasagesse.com/wp-content/uploads/2020/10/06143514/30-1-570x570.jpg",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Antioxidant, antimicrobial",
  },
  {
    id: 24,
    name: "Dandelion",
    origin: "Eurasia, North America",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://png.pngtree.com/thumb_back/fw800/background/20230727/pngtree-dandelions-in-a-field-with-blown-pollen-image_10209352.jpg",
video: "",
    purpose: "Medicinal, culinary",
    medicinalProperty: "Liver detoxification, diuretic",
  },
  {
    id: 25,
    name: "Hibiscus",
    origin: "Tropical, subtropical",
    climaticCondition: "Tropical, warm",
    availability: "Common",
    image: "https://www.nzherald.co.nz/resizer/v2/ABJCTA4W7E2C3AU3EQZWALJSC4.jpg?auth=d8aaa3420f7df6ac1cf2aa72abab4e455cd965183cff05b59a7c318db7c0e951&width=576&height=613&quality=70&smart=true",
video: "",
    purpose: "Ornamental, medicinal",
    medicinalProperty: "Blood pressure regulation, antioxidant",
  },
  {
    id: 26,
    name: "Calendula",
    origin: "Mediterranean",
    climaticCondition: "Temperate, moist",
    availability: "Common",
    image: "https://media.istockphoto.com/id/500120331/photo/calendula-medicinal-plant.jpg?s=612x612&w=0&k=20&c=y3HclUxZKVdKLQnVCmlF4wpO6wK4hTevgJcurbb9ji8=",
video: "",
    purpose: "Medicinal, ornamental",
    medicinalProperty: "Skin healing, anti-inflammatory",
  },
  {
    id: 27,
    name: "Valerian",
    origin: "Europe, Asia",
    climaticCondition: "Temperate, moist",
    availability: "Common",
    image: "https://media.istockphoto.com/id/518879523/photo/valeriana.jpg?s=612x612&w=0&k=20&c=q7VtYSs0voIH_CR6DUkuJYdGzGBocewY2NaDmQwncj4=",
video: "",
    purpose: "Medicinal",
    medicinalProperty: "Sleep aid, anxiety reduction",
  },
  {
    id: 28,
    name: "Catnip",
    origin: "Europe, Asia",
    climaticCondition: "Temperate, moist",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1212160249/photo/catnip-flowers-field-in-summer.jpg?s=612x612&w=0&k=20&c=zic5cKJXgS0Z-GtoP-KdegHwW1HmkHzclYcL07ofQqg=",
video: "",
    purpose: "Medicinal, ornamental",
    medicinalProperty: "Digestive aid, anxiety relief",
  },
  {
    id: 29,
    name: "Fennel",
    origin: "Mediterranean",
    climaticCondition: "Temperate, dry",
    availability: "Common",
    image: "https://media.istockphoto.com/id/157606208/photo/close-up-of-organic-fennel-plants-growing-on-rural-farm.jpg?s=612x612&w=0&k=20&c=_SItcuMJ2btOaZozLgH24ATbNQN7V6kqNgmoatbQ_ec=",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Digestive aid, anti-inflammatory",
  },
  {
    id: 30,
    name: "Yarrow",
    origin: "Europe, Asia, North America",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1164968192/photo/white-meadow-flower-yarrow-on-natural-background.jpg?s=612x612&w=0&k=20&c=Ch7QgGWG7xt3cJypW0THZEcmQXwc6XUfQ9AXW3eyWTk=",
video: "",
    purpose: "Medicinal, ornamental",
    medicinalProperty: "Wound healing, anti-inflammatory",
  },
  {
    id: 31,
    name: "Bergamot",
    origin: "Mediterranean",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1265531294/photo/monarda-fistulosa-wild-bergamot-or-bee-balm-pink-wildflower-in-the-mint-family-lamiaceae.jpg?s=612x612&w=0&k=20&c=M3USf37kDQYT8n0JN_dWWTCMm9egGtgfGIW56CA53Po=",
video: "",
    purpose: "Aromatherapy, culinary",
    medicinalProperty: "Stress relief, digestive aid",
  },
  {
    id: 32,
    name: "Rhubarb",
    origin: "Asia, Europe",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1051365496/photo/rhubarb.jpg?s=612x612&w=0&k=20&c=dDT-VGF1GdyJvD-2PW9nLiUiYkxYGazWLKYKN8DKPVw=",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Digestive aid, laxative",
  },
  {
    id: 33,
    name: "Chicory",
    origin: "Mediterranean",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://t3.ftcdn.net/jpg/04/72/61/70/360_F_472617073_RazRARtQ9CCNkVqWoENsF7BrVpypUO0E.jpg",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Liver health, digestive aid",
  },
  {
    id: 34,
    name: "Moringa",
    origin: "India, Africa",
    climaticCondition: "Tropical, warm",
    availability: "Common",
    image: "https://m.media-amazon.com/images/I/71Qziey7TIL.AC_UF1000,1000_QL80.jpg",
video: "",
    purpose: "Medicinal, nutritional",
    medicinalProperty: "Nutrient-rich, anti-inflammatory",
  },
  {
    id: 35,
    name: "Psyllium",
    origin: "Asia",
    climaticCondition: "Tropical, warm",
    availability: "Common",
    image: "https://media.istockphoto.com/id/528480640/photo/plantago-ovata-psyllium.jpg?s=612x612&w=0&k=20&c=Qp29IRAJwrTMP1TbKAeDHjCOzbekCM-SBMhokWlwf8I=",
video: "",
    purpose: "Medicinal",
    medicinalProperty: "Digestive aid, laxative",
  },
  {
    id: 36,
    name: "Ginkgo Biloba",
    origin: "China",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "",
video: "",
    purpose: "Medicinal",
    medicinalProperty: "Cognitive support, circulatory health",
  },
  {
    id: 37,
    name: "Nettle",
    origin: "Europe, Asia",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1055535566/photo/ginkgo-biloba-tree-in-diminishing-perspective-in-the-fall.jpg?s=612x612&w=0&k=20&c=K9vHVawgHJ0DLkzDMECox1kOwrtM2xmdvSphIoyOn-o=",
video: "",
    purpose: "Medicinal, culinary",
    medicinalProperty: "Anti-inflammatory, diuretic",
  },
  {
    id: 38,
    name: "Dill",
    origin: "Mediterranean",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://cdn.mos.cms.futurecdn.net/SDv2LPJFz8475crV6djrNG-320-80.jpg",
video: "",
    purpose: "Culinary, medicinal",
    medicinalProperty: "Digestive aid, anti-inflammatory",
  },
  {
    id: 39,
    name: "Lemon Balm",
    origin: "Europe",
    climaticCondition: "Temperate, moist",
    availability: "Common",
    image: "https://img.freepik.com/premium-photo/lemon-balm-plant-pot-white-background_960080-29326.jpg",
video: "",
    purpose: "Medicinal, culinary",
    medicinalProperty: "Calms anxiety, aids digestion",
  },
  {
    id: 40,
    name: "Hawthorn",
    origin: "Europe, Asia",
    climaticCondition: "Temperate",
    availability: "Common",
    image: "https://media.istockphoto.com/id/1300292960/photo/hawthorn-in-bloom.jpg?s=612x612&w=0&k=20&c=22e5z5gKks86GPpJmuNO-QkO6Qb9GsHF5iC9L6qtufQ=",
video: "",
    purpose: "Medicinal",
    medicinalProperty: "Heart health, blood pressure regulation",
  },
]